[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin=node_modules/@openzeppelin', "@chainlink/contracts/=node_modules/@chainlink/contracts/"]

[invariant]
runs = 128
depth = 128 # number of calls in a single run
fail_on_revert = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
